# [CptS 215 Data Analytics Systems and Algorithms](https://piazza.com/wsu/fall2017/cpts215/home)
[Washington State University](https://wsu.edu)

[Srini Badri](https://school.eecs.wsu.edu/people/faculty/), [Gina Sprint](http://eecs.wsu.edu/~gsprint/)

## MA5 Tree Practice (50 pts)

<mark>Author: Nam Jun Lee</mark>

<mark>Date: November 1st, 2021</mark>

### Learner Objectives
At the conclusion of this micro assignment, participants should be able to:
* Implement/analyze trees
    * Binary trees
    * Binary search trees
    * AVL trees

### Prerequisites
Before starting this micro assignment, participants should be able to:
* Write object oriented Python code
* Write Markdown and code cells in Jupyter Notebook
* Perform algorithm analysis

### Acknowledgments
Content used in this assignment is based upon information in the following sources:
* [Data Structures: Abstraction and Design Using Java](http://www.wiley.com/WileyCDA/WileyTitle/productCd-EHEP001607.html) by Koffman and Wolfgang

## Overview and Requirements
For this micro assignment, you are going to download this Jupyter Notebook and answer the following questions. Your answer for a problem should be in a cell *immediately* after the problem cell. *Do not modify the problem cell.*

We are going to solve several problems related to trees and their efficiency. This micro assignment includes conceptional questions and programming.

### Conceptual Questions (38 pts)
Solve the following problems and *justify* your answers:

#### 1. For the following binary tree:
<img src="https://raw.githubusercontent.com/gsprint23/cpts215/master/microassignments/figures/ma5_tree.png" width="400"/>

   1. (2 pts) Is the tree full?  
   1. (2 pts) Is the tree complete? 
   1. (2 pts) What is the tree's height? 
   1. List the nodes in the tree in the order they would be visited during a: 
        1. (4 pts) Pre-order traversal
        1. (4 pts) Level-order traversal
        1. (4 pts) Post-order traversal
        1. (4 pts) In-order traversal

#### Question 1 Answer:

1. Following binary tree:
    
  1. Is the tree full?  
     + This binary tree is filled with the bottom level full.
     + Thus, `Yes` 
  1. Is the tree complete?  
     + This binary tree is full of nodes at the lower level and is filled with nodes from left to right within the same level.
     + Thus, `Yes`  
  1. What is the tree's height?  
     + It is called increasing the maximum value of the leaf level. The level of the root is zero, and each time the branch goes down one by one, the level increases by one.   
     + Therefore, the height of this binary tree is `3`.  
  1. List the nodes in the tree in the order they would be visited during a:  
     1. Pre-order traversal:  
          * The pre-order starts with the root and visits the current node to perform tasks on the data. Visiting working from left to right. (Node - Left children - Right children)  
          * Thus, `*, A, 1, X, Y, 2, B, 3, 4`  
     1. Level-order traversal: 
          * The level-order starts with the root, visit all of the nodes on the current level left to right, then move to the lower level.  
          * Thus, `*, A, B, 1, 2, 3, 4, X, Y`  
     1. Post-order traversal:  
          * The post-order starts with the root, visit all children first, then visit the node and do something with the data. (Left children - Right children - Node)  
          * Thus, `X, Y, 1, 2, A, 3, 4, B, *`  
     1. In-order traversal:  
          * The in-order starts with the root, visit all the children on the left children on the left. If all the left sub-items of the node have visited, visit the children on the right. (Left children - Node - Right children)  
          * Thus, `X, 1, Y, A, 2, *, 3, B, 4`

#### 2. (2 pts) What is the time complexity to search a full BST?

#### Question 2 Answer:

The time complexity for searching for the full BST is $\mathcal{O}(log N)$. However, in the worst case, it can vary depending on the height of the tree because it searches to the Leaf node $\mathcal{O}(h)$.  
* Thus, $\mathcal{O}(log N)$ OR $\mathcal{O}(h)$

#### 3. The following questions refer to the same BST. The operations are cumulative:
   A. (2 pts) Show the BST that would result from inserting the items 35, 20, 30, 50, 45, 60, 18, 25 in this sequence.  
   B. (2 pts) Show the BST that would result after removing item 35 (promote in order successor).  
   C. (2 pts) Show the BST that would result after removing item 18 (promote in order successor).  
   D. (2 pts) How would the trees in the previous problems look differently if we promote in order predecessors instead of successors?  

#### Question 3 Answer:

3. following questions refer to the same BST:  
    1. Show the BST that would result from inserting the items 35, 20, 30, 50, 45, 60, 18, 25 in this sequence:  
                       
                    [35]
                 /        \
               [20]      [50]
              /    \    /    \
            [18] [30] [45] [60]
                  /  
               [25]
               
    1. Show the BST that would result after removing item 35 (promote in order successor):  
                     
                    [45]
                 /        \
               [20]      [50]
              /    \         \ 
            [18]  [30]        [60]
                  /
                [25]
                
    1. Show the BST that would result after removing item 18 (promote in order successor):  
    
                    [45]
                 /        \
               [20]      [50]
                   \         \
                   [30]      [60]
                  /
                [25]                                                                                               
    1. How would the trees in the previous problems look differently if we promote in order predecessors instead of successors?
    
        * Show the BST that would result after removing item 35:

                        [30]
                     /        \
                   [20]      [50]
                  /    \    /    \
                [18]  [25] [45]  [60]

        * Show the BST that would result after removing item 18:

                        [30]
                     /        \
                   [20]       [50]
                       \     /    \
                      [25] [45]   [60]  
 

#### 4. (3 pts) Given the following tree, perform the appropriate rotations to bring it back into balance:

<img src="https://runestone.academy/runestone/books/published/pythonds/_images/rotexer1.png" width="200"/>  
(image from [https://runestone.academy/runestone/books/published/pythonds/_images/rotexer1.png])


#### Question 4 Answer:
Perform the appropriate rotations to bring it back into balance:

Given tree:  
                 
                [B(-2)]
               /       \
            [A(0)]    [E(1)]
                     /      \
                  [D(1)]  [F(0)]
                 /
              [C(0)]  

Right rotation:  
       
               [B(-2)]
              /       \
           [A(0)]    [D(-1)]
                    /      \
                 [C(0)]   [E(-1)] 
                                \
                               [F(0)] 
                             
Left rotation:

              [D(0)]
             /       \
         [B(0)]     [E(-1)]
        /     \           \
     [A(0)] [C(0)]       [F(0)]  

#### 5. (3 pts) Give the function calls of `BinaryTree` class (from lecture notes) to build the following tree:

<img src="https://runestone.academy/runestone/books/published/pythonds/_images/exerTree.png" width="450"/>

(image from [https://runestone.academy/runestone/books/published/pythonds/_images/exerTree.png])

#### Question 5 Answer:
Using BinaryTree class (from lecture notes) to build the following tree:

In [60]:
# a class representing a BinaryTree
class BinaryTree:
    def __init__(self, root_data=None, left_child=None, right_child=None):
        self.root_data = root_data
        self.left_child = left_child
        self.right_child = right_child

    # if root is empy then return True
    def is_empty(self):
        return self.root_data is None
    
    # insert child to left
    def insert_left(self, new_data):
        if self.left_child is None:
            self.left_child = BinaryTree(new_data)
        else:
            temp = BinaryTree(new_data)
            temp.left_child = self.left_child
            self.left_child = temp
    
    # insert child to right
    def insert_right(self, new_data):
        if self.right_child is None:
            self.right_child = BinaryTree(new_data)
        else:
            temp = BinaryTree(new_data)
            temp.right_child = self.right_child
            self.right_child = temp
    
    # traversal by level
    def level_order_traversal(self):
        if not self.is_empty():
            lst = [self.root_data]
            self.level_order_helper(self, lst)
            for l in lst:
                print(l, end=" -> ")
            print()
        else:
            print("Empty tree")
    
    # help traversal by level
    def level_order_helper(self, val, lv):
        if val is not None:
            if val.left_child is not None:
                lv.append(val.left_child.root_data)
            if val.right_child is not None:
                lv.append(val.right_child.root_data)
            self.level_order_helper(val.left_child, lv)
            self.level_order_helper(val.right_child, lv)



In [61]:
# instance method
tree = BinaryTree(root_data='language')
# insert the content given to the question and test it.
tree.insert_left('Java')
tree.insert_left('C')
tree.insert_right('Scheme')
tree.insert_right('Python')
tree.insert_right('interpreted')
tree.insert_left('compiled')

print("Level-order traversal:")
tree.level_order_traversal()

Level-order traversal:
language -> compiled -> interpreted -> C -> Java -> Python -> Scheme -> 


### Implementation Question (10 pts)

Implement a Binary Search Tree data structure using the code provided in the lecture notes or <i>Miller and Ranum</i> textbook. Update the implementation as described below:
* (9 pts) Add `pre_order_traversal()` and `post_order_traversal()` methods to print the `key` and `value` pairs in preorder and postorder respectively. 
* (1 pts) Include curly brackets `{ }` and commas seperator `,` in the print results.

Test your implementation using the following sequence of code:

#### Implementation Question Answer
Using the code provided in the lecture notes & Miller and Ranum textbook.

In [62]:
# a class representing a BSTNode
class BSTNode:
    def __init__(self, key, val, left=None, right=None, parent=None):
        self.key = key
        self.value = val
        self.left_child = left
        self.right_child = right
        self.parent = parent

    def __iter__(self):
        if self:
            if self.has_left_child():
                for elem in self.left_child:
                    yield elem
            yield self.key
            if self.has_right_child():
                for elem in self.right_child:
                    yield elem
    
    def has_left_child(self):
        return self.left_child

    def has_right_child(self):
        return self.right_child

# a class representing a BinarySearchTree
class BinarySearchTree:
    def __init__(self):
        self.root = None
        self.size = 0

    def __iter__(self):
        return self.root.__iter__()
    
    # put key and value in tree
    def put(self, key, val):
        if self.root:
            self._put(key, val, self.root)
        else:
            self.root = BSTNode(key, val)
        self.size = self.size + 1
    
    # help put function
    def _put(self, key, val, current_node):
        if key == current_node.key:  # handle duplicates by updating value
            current_node.value = val
        elif key < current_node.key:
            if current_node.has_left_child():
                self._put(key, val, current_node.left_child)
            else:
                current_node.left_child = BSTNode(key, val, parent=current_node)
        else:
            if current_node.has_right_child():
                self._put(key, val, current_node.right_child)
            else:
                current_node.right_child = BSTNode(key, val, parent=current_node)
    
    # update pre_order_traversal() methods to print the key and value pairs in preorder
    def pre_order_traversal(self):
        if self.size > 0:
            self.pre_order_helper(self.root)
            print()
        else:
            print("Empty Tree")
    
    # help pre-order traversal function; include curly brackets { } and commas seperator , in the print results.
    def pre_order_helper(self, current_node):
        if current_node is not None:
            print("{" + str(current_node.key) + ":" + str(current_node.value) + "}", end=", ")
            self.pre_order_helper(current_node.left_child)
            self.pre_order_helper(current_node.right_child)

    # update post_order_traversal() methods to print the key and value pairs in postorder
    def post_order_traversal(self):
        if self.size > 0:
            self.post_order_helper(self.root)
            print()
        else:
            print("Empty Tree")
            
    # help pre-order traversal function; include curly brackets { } and commas seperator , in the print results.
    def post_order_helper(self, current_node):
        if current_node is not None:
            self.post_order_helper(current_node.left_child)
            self.post_order_helper(current_node.right_child)
            print("{" + str(current_node.key) + ":" + str(current_node.value) + "}", end=", ")

In [63]:
# instance method
myTree = BinarySearchTree()

In [64]:
# Test code for pre-order and post-order traversal methods
myTree.put(122, "C++ Data Structures")
myTree.put(131, "Java Programming")
myTree.put(115, "Intro to DA")
myTree.put(215, "Data Structures & Algorithms")
myTree.put(121, "C Programming")
myTree.put(132, "Java Data Structures")

print('Pre-order traversal:\n')
myTree.pre_order_traversal()
print('\nPost-order traversal:\n')
myTree.post_order_traversal()

Pre-order traversal:

{122:C++ Data Structures}, {115:Intro to DA}, {121:C Programming}, {131:Java Programming}, {215:Data Structures & Algorithms}, {132:Java Data Structures}, 

Post-order traversal:

{121:C Programming}, {115:Intro to DA}, {132:Java Data Structures}, {215:Data Structures & Algorithms}, {131:Java Programming}, {122:C++ Data Structures}, 


Here is the expected print output for pre_order_traversal() method:

<i>{122:C++ Data Structures, 115:Intro to DA, 121:C Programming, 131:Java Programming, 215:Data Structures & Algorithms, 132:Java Data Structures}</i>


Here is the expected print output for post_order_travesal() method:

<i>{121:C Programming, 115:Intro to DA, 132:Java Data Structures, 215:Data Structures & Algorithms, 131:Java Programming, 122:C++ Data Structures}</i>

## Submitting Assignments
1.	Use the Blackboard tool https://learn.wsu.edu to submit your assignment. You will submit your code to the corresponding programming assignment under the "Content" tab. You must upload your solutions as `<your last name>_ma5.zip` by the due date and time.
2.	Your .zip file should contain your .ipynb file and a .html file representing your Notebook as a webpage (File->Download as->HTML).

## Grading Guidelines
This assignment is worth 50 points. Your assignment will be evaluated based on a successful compilation and adherence to the program requirements. We will grade according to the following criteria:
* 38 pts for correct answers to the conception questions
* 10 pts for correct implementation of Binary Search Tree `pre_order_traversal()` and `post_order_traversal()` methods
* 2 pts for for adherence to proper programming style and comments established for the class